'use strict';

export const RECEIVE_ALBUMS = 'RECEIVE_ALBUMS';
export const RECEIVE_ALBUM = 'RECEIVE_ALBUM';

export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS';
export const RECEIVE_ARTIST = 'RECEIVE_ARTIST';

export const START_PLAYING = 'START_PLAYING';
export const STOP_PLAYING = 'STOP_PLAYING';
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const CLEAR_CURRENT_SONG = 'CLEAR_CURRENT_SONG';
export const SET_LIST = 'SET_LIST';
export const CLEAR_LIST = 'CLEAR_LIST';
export const SET_PROGRESS = 'SET_PROGRESS';
export const CLEAR_PROGRESS = 'CLEAR_PROGRESS';
export const NEXT_SONG = 'NEXT_SONG';
export const PREVIOUS_SONG = 'PREVIOUS_SONG';

export const SWITCH_LOCATION = 'SWITCH_LOCATION';